import { Link, useRouterState } from "@tanstack/react-router";
import { motion } from "motion/react";
import { Building2, Check, Clock3, Heart, Home, LayoutDashboard, LocateFixed, Map, MapPin, Menu, Search, SlidersHorizontal, Sparkles, UserRound, X, Zap } from "lucide-react";
import { useState, type ReactNode } from "react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";
import { formatRent, type Property } from "@/lib/vacanza-data";
import { useVacanza } from "./vacanza-store";

export function Logo() { return <Link to="/" className="flex items-center gap-2 font-display text-xl font-extrabold tracking-normal"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground"><Building2 className="size-4" /></span>VACANZA</Link>; }

const nav = [{ label: "Home", to: "/" }, { label: "Find a Home", to: "/find" }, { label: "List Property", to: "/list-property" }, { label: "How It Works", to: "/how-it-works" }, { label: "About", to: "/about" }] as const;
export function Navbar() {
  const [open, setOpen] = useState(false);
  return <header className="sticky top-0 z-40 border-b border-border/70 bg-background/95 backdrop-blur"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-4 sm:px-6 lg:px-8"><Logo /><nav className="hidden items-center gap-7 lg:flex">{nav.map((item) => <Link key={item.to} to={item.to} className="text-sm font-medium text-muted-foreground transition-colors hover:text-foreground" activeProps={{ className: "text-foreground" }}>{item.label}</Link>)}</nav><div className="hidden items-center gap-2 lg:flex"><Button asChild variant="ghost"><Link to="/find">I'm a Renter</Link></Button><Button asChild><Link to="/owner">I'm an Owner</Link></Button></div><Button aria-label="Open navigation" size="icon" variant="ghost" className="lg:hidden" onClick={() => setOpen(!open)}>{open ? <X /> : <Menu />}</Button></div>{open && <div className="border-t bg-background px-4 py-4 lg:hidden">{nav.map((item) => <Link key={item.to} to={item.to} onClick={() => setOpen(false)} className="block border-b py-3 text-sm font-semibold">{item.label}</Link>)}<div className="mt-4 grid grid-cols-2 gap-2"><Button asChild variant="outline"><Link to="/find">Renter</Link></Button><Button asChild><Link to="/owner">Owner</Link></Button></div></div>}</header>;
}

export function BottomNav() {
  const pathname = useRouterState({ select: (s) => s.location.pathname });
  const items = [{ label: "Home", to: "/", icon: Home }, { label: "Search", to: "/find", icon: Search }, { label: "Saved", to: "/saved", icon: Heart }, { label: "Dashboard", to: "/owner", icon: LayoutDashboard }] as const;
  return <nav className="fixed inset-x-0 bottom-0 z-50 grid grid-cols-4 border-t bg-background/96 px-2 pb-[max(.5rem,env(safe-area-inset-bottom))] pt-2 backdrop-blur lg:hidden">{items.map(({ label, to, icon: Icon }) => <Link key={to} to={to} className={cn("flex flex-col items-center gap-1 text-[11px] font-semibold", pathname === to ? "text-primary" : "text-muted-foreground")}><Icon className="size-5" />{label}</Link>)}</nav>;
}

export function AppShell({ children, marketing = false }: { children: ReactNode; marketing?: boolean }) { return <><Navbar /><main className="pb-20 lg:pb-0">{children}</main>{marketing && <Footer />}<BottomNav /></>; }
export function Footer() { return <footer className="border-t bg-foreground py-12 text-background"><div className="mx-auto grid max-w-7xl gap-8 px-4 sm:px-6 md:grid-cols-2 lg:px-8"><div><div className="text-xl font-extrabold">VACANZA</div><p className="mt-3 max-w-sm text-sm text-background/65">Find what's vacant. Right now. Around you.</p></div><div className="flex gap-6 text-sm md:justify-end"><Link to="/find">Find a home</Link><Link to="/list-property">List property</Link><Link to="/about">About</Link></div></div></footer>; }

export function PageIntro({ eyebrow, title, copy, action }: { eyebrow?: string; title: string; copy: string; action?: ReactNode }) { return <div className="grid grid-cols-[minmax(0,1fr)_auto] items-end gap-5"><div className="min-w-0">{eyebrow && <p className="mb-2 text-xs font-bold uppercase text-primary">{eyebrow}</p>}<h1 className="font-display text-3xl font-extrabold sm:text-4xl">{title}</h1><p className="mt-2 max-w-2xl text-muted-foreground">{copy}</p></div>{action}</div>; }

export function StatusBadge({ property, large = false }: { property: Property; large?: boolean }) {
  const stale = property.stale;
  return <span className={cn("inline-flex items-center gap-2 rounded-full px-3 py-1.5 font-bold uppercase", large ? "text-sm" : "text-xs", stale ? "bg-warning-soft text-warning" : property.status === "vacant" ? "bg-success-soft text-success" : "bg-danger-soft text-danger")}><span className={cn("size-2 rounded-full", stale ? "bg-warning" : property.status === "vacant" ? "bg-success" : "bg-danger")} />{stale ? "Not recently verified" : property.status}</span>;
}
export function Freshness({ property }: { property: Property }) { return <div className={cn("flex items-center gap-1.5 text-xs font-semibold", property.stale ? "text-warning" : "text-muted-foreground")}><Clock3 className="size-3.5" />{property.stale ? `Last verified ${property.lastUpdated}` : `Verified ${property.lastUpdated}`}</div>; }

export function PropertyCard({ property, compact = false }: { property: Property; compact?: boolean }) {
  const { saved, toggleSaved } = useVacanza(); const isSaved = saved.includes(property.id);
  return <motion.article layout whileHover={{ y: -3 }} className={cn("group overflow-hidden rounded-card border bg-card shadow-card transition-shadow hover:shadow-card-hover", compact ? "sm:grid sm:grid-cols-[190px_1fr]" : "")}> <div className={cn("relative overflow-hidden", compact ? "h-48 sm:h-full" : "aspect-[16/10]")}><img src={property.images[0]} alt={property.title} loading="lazy" width={1408} height={912} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.03]" /><div className="absolute left-3 top-3"><StatusBadge property={property} /></div><Button size="icon" variant="secondary" aria-label={isSaved ? "Remove saved property" : "Save property"} className="absolute right-3 top-3 rounded-full" onClick={() => { toggleSaved(property.id); toast.success(isSaved ? "Removed from saved properties" : "Property saved"); }}><Heart className={cn(isSaved && "fill-current text-danger")} /></Button></div><div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><h3 className="truncate text-lg font-bold">{property.title}</h3><p className="mt-1 text-sm text-muted-foreground">{property.bhk} · {property.furnished ? "Furnished" : "Unfurnished"}</p></div><p className="shrink-0 font-bold">{formatRent(property.rent)}<span className="text-xs font-normal text-muted-foreground">/mo</span></p></div><p className="mt-3 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin className="size-4 shrink-0" />{property.location}, {property.city}</p><div className="mt-3"><Freshness property={property} /></div><div className="mt-4 grid grid-cols-2 gap-2"><Button asChild><Link to="/property/$propertyId" params={{ propertyId: property.id }}>View Property</Link></Button><Button variant="outline" onClick={() => toast.success(`Contact request sent to ${property.ownerName}`)}>Contact Owner</Button></div></div></motion.article>;
}

export function MapView({ properties, selectedId, onSelect, className }: { properties: Property[]; selectedId?: string; onSelect?: (id: string) => void; className?: string }) {
  const selected = properties.find((p) => p.id === selectedId) ?? properties[0];
  return <div className={cn("relative min-h-[430px] overflow-hidden rounded-card border bg-map", className)}><div className="absolute inset-0 map-grid" /><div className="absolute left-4 top-4 z-10 flex gap-2"><Button size="sm" variant="secondary"><LocateFixed />Near me</Button><Button size="sm">Search this area</Button></div>{properties.map((p) => <button key={p.id} aria-label={`Show ${p.title}`} onClick={() => onSelect?.(p.id)} className={cn("absolute z-10 grid size-9 -translate-x-1/2 -translate-y-1/2 place-items-center rounded-full border-4 border-background shadow-lg transition-transform hover:scale-110", p.stale ? "bg-warning" : p.status === "vacant" ? "bg-success" : "bg-danger", selected?.id === p.id && "scale-125 ring-4 ring-background/70")} style={{ left: `${p.coordinates.x}%`, top: `${p.coordinates.y}%` }}><Home className="size-4 text-primary-foreground" /></button>)}{selected && <motion.div key={selected.id} initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} className="absolute bottom-4 left-4 right-4 z-20 max-w-sm rounded-card border bg-background p-3 shadow-xl"><div className="grid grid-cols-[72px_1fr_auto] gap-3"><img src={selected.images[0]} alt="" className="h-16 w-[72px] rounded-md object-cover" /><div className="min-w-0"><p className="truncate font-bold">{selected.title}</p><p className="text-xs text-muted-foreground">{selected.bhk} · {formatRent(selected.rent)}</p><div className="mt-1"><Freshness property={selected} /></div></div><Button asChild size="icon" variant="ghost"><Link to="/property/$propertyId" params={{ propertyId: selected.id }}><MapPin /></Link></Button></div></motion.div>}</div>;
}

export function EmptyState({ title = "No properties found", copy = "Try changing your search or filters to see more homes." }: { title?: string; copy?: string }) { return <div className="grid min-h-72 place-items-center rounded-card border border-dashed bg-muted/40 p-8 text-center"><div><span className="mx-auto grid size-14 place-items-center rounded-full bg-background shadow-sm"><Search className="text-muted-foreground" /></span><h3 className="mt-4 font-bold">{title}</h3><p className="mt-1 max-w-sm text-sm text-muted-foreground">{copy}</p></div></div>; }
export function StatCard({ label, value, tone = "default" }: { label: string; value: number; tone?: "default" | "success" | "danger" }) { return <div className="border-l-2 border-border py-2 pl-5"><p className="text-sm text-muted-foreground">{label}</p><p className={cn("mt-1 text-3xl font-extrabold", tone === "success" && "text-success", tone === "danger" && "text-danger")}>{value}</p></div>; }
export const ValueIcon = ({ type }: { type: "live" | "owner" | "location" | "contact" }) => { const icons = { live: Zap, owner: UserRound, location: MapPin, contact: Check }; const Icon = icons[type]; return <span className="grid size-10 place-items-center rounded-lg bg-success-soft text-success"><Icon className="size-5" /></span>; };
export { Search, SlidersHorizontal, Map, Sparkles };