/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FindRouteImport } from './routes/find'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as ListPropertyRouteImport } from './routes/list-property'
import { Route as OwnerRouteImport } from './routes/owner'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as PropertyPropertyIdRouteImport } from './routes/property.$propertyId'
import { Route as OwnerPropertyPropertyIdRouteImport } from './routes/owner.property.$propertyId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FindRoute = FindRouteImport.update({
  id: '/find',
  path: '/find',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPropertyRoute = ListPropertyRouteImport.update({
  id: '/list-property',
  path: '/list-property',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerRoute = OwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyPropertyIdRoute = PropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnerPropertyPropertyIdRoute = OwnerPropertyPropertyIdRouteImport.update({
  id: '/property/$propertyId',
  path: '/property/$propertyId',
  getParentRoute: () => OwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/find': typeof FindRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/owner': typeof OwnerRouteWithChildren
  '/saved': typeof SavedRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/owner/property/$propertyId': typeof OwnerPropertyPropertyIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/find': typeof FindRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/owner': typeof OwnerRouteWithChildren
  '/saved': typeof SavedRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/owner/property/$propertyId': typeof OwnerPropertyPropertyIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/find': typeof FindRoute
  '/how-it-works': typeof HowItWorksRoute
  '/list-property': typeof ListPropertyRoute
  '/owner': typeof OwnerRouteWithChildren
  '/saved': typeof SavedRoute
  '/property/$propertyId': typeof PropertyPropertyIdRoute
  '/owner/property/$propertyId': typeof OwnerPropertyPropertyIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/find'
    | '/how-it-works'
    | '/list-property'
    | '/owner'
    | '/saved'
    | '/property/$propertyId'
    | '/owner/property/$propertyId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/find'
    | '/how-it-works'
    | '/list-property'
    | '/owner'
    | '/saved'
    | '/property/$propertyId'
    | '/owner/property/$propertyId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/find'
    | '/how-it-works'
    | '/list-property'
    | '/owner'
    | '/saved'
    | '/property/$propertyId'
    | '/owner/property/$propertyId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  FindRoute: typeof FindRoute
  HowItWorksRoute: typeof HowItWorksRoute
  ListPropertyRoute: typeof ListPropertyRoute
  OwnerRoute: typeof OwnerRouteWithChildren
  SavedRoute: typeof SavedRoute
  PropertyPropertyIdRoute: typeof PropertyPropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find': {
      id: '/find'
      path: '/find'
      fullPath: '/find'
      preLoaderRoute: typeof FindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-property': {
      id: '/list-property'
      path: '/list-property'
      fullPath: '/list-property'
      preLoaderRoute: typeof ListPropertyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner': {
      id: '/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof OwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$propertyId': {
      id: '/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/property/$propertyId'
      preLoaderRoute: typeof PropertyPropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owner/property/$propertyId': {
      id: '/owner/property/$propertyId'
      path: '/property/$propertyId'
      fullPath: '/owner/property/$propertyId'
      preLoaderRoute: typeof OwnerPropertyPropertyIdRouteImport
      parentRoute: typeof OwnerRoute
    }
  }
}

interface OwnerRouteChildren {
  OwnerPropertyPropertyIdRoute: typeof OwnerPropertyPropertyIdRoute
}

const OwnerRouteChildren: OwnerRouteChildren = {
  OwnerPropertyPropertyIdRoute: OwnerPropertyPropertyIdRoute,
}

const OwnerRouteWithChildren = OwnerRoute._addFileChildren(OwnerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  FindRoute: FindRoute,
  HowItWorksRoute: HowItWorksRoute,
  ListPropertyRoute: ListPropertyRoute,
  OwnerRoute: OwnerRouteWithChildren,
  SavedRoute: SavedRoute,
  PropertyPropertyIdRoute: PropertyPropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
